# Generated by Django 2.2.4 on 2019-10-27 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgAccessRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.TextField(null=True)),
                ('pending', models.BooleanField(default=True)),
                ('accepted', models.BooleanField(default=False)),
                ('cause_of_rejection', models.TextField(default='')),
                ('requested_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('process_completed_on', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
