# Generated by Django 2.2.4 on 2019-09-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20190909_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='organisation',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='organisation_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='pending_for_screening',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
