# Generated by Django 2.2.4 on 2019-10-24 04:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesmodel',
            name='photos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=''), null=True, size=None),
        ),
    ]
