# Generated by Django 2.2.4 on 2019-10-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_auto_20191024_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticArticleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('content', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaticCategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('sub_categories', models.ManyToManyField(related_name='_staticcategorymodel_sub_categories_+', to='administrator.StaticCategoryModel')),
            ],
        ),
    ]
