# Generated by Django 2.2.4 on 2019-10-30 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_auto_20191030_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlesmodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.ArticleCategoryModel'),
        ),
    ]
