# Generated by Django 2.2.4 on 2019-12-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_articlesmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticcategorymodel',
            name='head_category',
            field=models.BooleanField(default=True),
        ),
    ]
