# Generated by Django 2.2.4 on 2019-12-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_staticcategorymodel_head_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecategorymodel',
            name='parent_category',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='articlecategorymodel',
            name='sub_categories',
            field=models.ManyToManyField(related_name='_articlecategorymodel_sub_categories_+', to='administrator.ArticleCategoryModel'),
        ),
    ]
