# Generated by Django 2.2.4 on 2020-01-16 06:13

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0008_auto_20191224_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlesmodel',
            name='videos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=''), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='articlesmodel',
            name='photos',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(default=''), null=True, size=None),
        ),
    ]
