# Generated by Django 2.2.4 on 2020-01-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0009_auto_20200116_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlesmodel',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
