# Generated by Django 3.2.4 on 2021-11-25 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0012_advideomodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='advideomodel',
            name='created',
            field=models.DateField(auto_now=True),
        ),
    ]
