# Generated by Django 3.2.8 on 2022-01-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0014_auto_20220129_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='adimagemodel',
            name='tender_image_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='adimagemodel',
            name='tender_image_secure_url',
            field=models.TextField(default=''),
        ),
    ]
