# Generated by Django 2.2.4 on 2019-09-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperAdminSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo_location_enabled', models.BooleanField(default=False)),
                ('google_places_enabled', models.BooleanField(default=False)),
                ('geo_tracking_enabled', models.BooleanField(default=False)),
                ('partner_app_enabled', models.BooleanField(default=False)),
                ('customer_app_enabled', models.BooleanField(default=False)),
                ('admin_dashboard_enabled', models.BooleanField(default=False)),
                ('image_upload_enabled', models.BooleanField(default=False)),
                ('geo_fencing_enabled', models.BooleanField(default=False)),
                ('services_enabled', models.BooleanField(default=False)),
                ('customer_signup_enabled', models.BooleanField(default=False)),
                ('partner_signup_enabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.TextField(default=''),
        ),
    ]
