# Generated by Django 2.2.4 on 2019-10-30 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_orgaccountmodel'),
        ('authentication', '0002_auto_20190907_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organisation.OrgAccountModel'),
        ),
    ]
